services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
    depends_on:
      - redis